//! `ail agent-guide` — print a CLAUDE.md / AGENTS.md snippet that
//! teaches an agent how to use ail in this project.
//!
//! Two tiers exist for the same reason `ail spec` has tiers: pasting
//! anything into CLAUDE.md spends tokens on every turn.
//!
//! - `claudemd` (default) — ~150-200 tokens. A table of the four or
//!   five commands an agent needs, with one-line "when to use" notes.
//!   This is what should land in most projects' CLAUDE.md.
//! - `claudemd-full` — ~800 tokens. The long-form briefing with
//!   passthrough explanation, validation-loop discussion, and a
//!   wider command table. Pick this only when the per-turn cost is
//!   justified by the audience (e.g. a teaching repo).
//!
//! Both snippets point at `ail spec --format compact` as the
//! canonical authoring reference rather than restating spec content,
//! so they stay small and resist drift. See SPEC §34.

use crate::command::CommandOutcome;

const CLAUDEMD_SNIPPET: &str = include_str!("claudemd.md");
const CLAUDEMD_FULL_SNIPPET: &str = include_str!("claudemd-full.md");

#[derive(Debug, Clone, Copy, Default)]
pub enum AgentGuideFormat {
    /// Lean CLAUDE.md / AGENTS.md snippet (~150-200 tokens). Default.
    #[default]
    Claudemd,
    /// Long-form CLAUDE.md / AGENTS.md briefing (~800 tokens). Opt-in.
    ClaudemdFull,
}

impl AgentGuideFormat {
    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "claudemd" | "agents-md" | "agentsmd" => Ok(AgentGuideFormat::Claudemd),
            "claudemd-full" | "agents-md-full" | "agentsmd-full" | "full" => {
                Ok(AgentGuideFormat::ClaudemdFull)
            }
            other => Err(format!(
                "unknown agent-guide format: '{other}' \
                 (expected: claudemd, claudemd-full)"
            )),
        }
    }
}

pub struct AgentGuideCommand {
    format: AgentGuideFormat,
}

impl AgentGuideCommand {
    pub fn new(format: AgentGuideFormat) -> Self {
        Self { format }
    }

    pub fn execute(&self) -> CommandOutcome {
        match self.format {
            AgentGuideFormat::Claudemd => print!("{CLAUDEMD_SNIPPET}"),
            AgentGuideFormat::ClaudemdFull => print!("{CLAUDEMD_FULL_SNIPPET}"),
        }
        CommandOutcome::Success
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- lean (default) snippet ---

    #[test]
    fn lean_snippet_is_small_enough_for_per_turn_inclusion() {
        // Hard ceiling: keep the default snippet under ~250 tokens
        // (~1000 bytes). Pasting anything larger into CLAUDE.md
        // taxes every turn for every project that adopts it.
        assert!(
            CLAUDEMD_SNIPPET.len() < 1100,
            "lean snippet is {} bytes — must stay under ~1000 to be \
             cheap enough for per-turn inclusion in CLAUDE.md",
            CLAUDEMD_SNIPPET.len()
        );
    }

    #[test]
    fn lean_snippet_starts_with_generated_marker() {
        assert!(
            CLAUDEMD_SNIPPET.starts_with("<!-- Generated by `ail agent-guide`"),
            "snippet must start with the generated-by marker so users \
             know it is safe to regenerate"
        );
    }

    #[test]
    fn lean_snippet_advertises_full_variant() {
        // Discoverability — readers of the lean snippet need to know
        // the long-form exists.
        assert!(
            CLAUDEMD_SNIPPET.contains("claudemd-full"),
            "lean snippet must mention the full-form opt-in so users \
             can find it when they need more depth"
        );
    }

    #[test]
    fn lean_snippet_references_compact_spec_format() {
        assert!(
            CLAUDEMD_SNIPPET.contains("ail spec --format compact"),
            "snippet must point at the canonical authoring reference"
        );
    }

    #[test]
    fn lean_snippet_references_validation_loop() {
        assert!(CLAUDEMD_SNIPPET.contains("ail validate"));
        assert!(CLAUDEMD_SNIPPET.contains("ail materialize"));
    }

    // --- full (opt-in) snippet ---

    #[test]
    fn full_snippet_is_substantially_longer_than_lean() {
        assert!(
            CLAUDEMD_FULL_SNIPPET.len() > CLAUDEMD_SNIPPET.len() * 3,
            "full snippet ({} bytes) should be at least 3x the lean \
             snippet ({} bytes); otherwise the two-tier split is not \
             paying for itself",
            CLAUDEMD_FULL_SNIPPET.len(),
            CLAUDEMD_SNIPPET.len()
        );
    }

    #[test]
    fn full_snippet_explains_passthrough_mode() {
        assert!(CLAUDEMD_FULL_SNIPPET.contains("passthrough"));
    }

    #[test]
    fn full_snippet_references_compact_spec_format() {
        assert!(CLAUDEMD_FULL_SNIPPET.contains("ail spec --format compact"));
    }

    // --- format parsing ---

    #[test]
    fn format_parses_default_aliases() {
        assert!(matches!(
            AgentGuideFormat::parse("claudemd"),
            Ok(AgentGuideFormat::Claudemd)
        ));
        assert!(matches!(
            AgentGuideFormat::parse("agents-md"),
            Ok(AgentGuideFormat::Claudemd)
        ));
    }

    #[test]
    fn format_parses_full_aliases() {
        assert!(matches!(
            AgentGuideFormat::parse("claudemd-full"),
            Ok(AgentGuideFormat::ClaudemdFull)
        ));
        assert!(matches!(
            AgentGuideFormat::parse("full"),
            Ok(AgentGuideFormat::ClaudemdFull)
        ));
    }

    #[test]
    fn format_rejects_unknown() {
        assert!(AgentGuideFormat::parse("readme").is_err());
    }
}
