//! `ail agent-guide` — print a CLAUDE.md (or AGENTS.md) snippet that
//! teaches an agent how to use ail in this project.
//!
//! The snippet is a curated artifact embedded at build time via
//! `include_str!`. It points at `ail spec --format compact` as the
//! canonical authoring reference rather than restating spec content,
//! so it stays small and resists drift. See SPEC §34.

use crate::command::CommandOutcome;

const CLAUDEMD_SNIPPET: &str = include_str!("claudemd.md");

#[derive(Debug, Clone, Copy, Default)]
pub enum AgentGuideFormat {
    /// CLAUDE.md-flavoured markdown (also valid for AGENTS.md).
    #[default]
    Claudemd,
}

impl AgentGuideFormat {
    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "claudemd" | "agents-md" | "agentsmd" => Ok(AgentGuideFormat::Claudemd),
            other => Err(format!(
                "unknown agent-guide format: '{other}' (expected: claudemd)"
            )),
        }
    }
}

pub struct AgentGuideCommand {
    format: AgentGuideFormat,
}

impl AgentGuideCommand {
    pub fn new(format: AgentGuideFormat) -> Self {
        Self { format }
    }

    pub fn execute(&self) -> CommandOutcome {
        match self.format {
            AgentGuideFormat::Claudemd => {
                print!("{CLAUDEMD_SNIPPET}");
            }
        }
        CommandOutcome::Success
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snippet_is_non_empty() {
        assert!(CLAUDEMD_SNIPPET.len() > 500);
    }

    #[test]
    fn snippet_references_compact_spec_format() {
        assert!(
            CLAUDEMD_SNIPPET.contains("ail spec --format compact"),
            "snippet must point at the canonical authoring reference"
        );
    }

    #[test]
    fn snippet_references_validation_loop() {
        assert!(CLAUDEMD_SNIPPET.contains("ail validate"));
        assert!(CLAUDEMD_SNIPPET.contains("ail materialize"));
    }

    #[test]
    fn snippet_explains_passthrough_mode() {
        assert!(CLAUDEMD_SNIPPET.contains("passthrough"));
    }

    #[test]
    fn snippet_starts_with_generated_marker() {
        assert!(
            CLAUDEMD_SNIPPET.starts_with("<!-- Generated by `ail agent-guide`"),
            "snippet must start with the generated-by marker so users \
             know it's safe to regenerate"
        );
    }

    #[test]
    fn format_parses_known_values() {
        assert!(matches!(
            AgentGuideFormat::parse("claudemd"),
            Ok(AgentGuideFormat::Claudemd)
        ));
        assert!(matches!(
            AgentGuideFormat::parse("agents-md"),
            Ok(AgentGuideFormat::Claudemd)
        ));
        assert!(AgentGuideFormat::parse("readme").is_err());
    }
}
