//! End-to-end tests for `ail agent-guide`. Exercises the binary
//! directly so we catch wiring regressions (clap, dispatch) that the
//! unit tests in `agent_guide::tests` cannot.

mod common;

use predicates::prelude::*;

#[test]
fn agent_guide_default_format_succeeds() {
    let (mut cmd, _home) = common::ail_cmd_isolated();
    cmd.arg("agent-guide");

    cmd.assert().success().stdout(predicates::str::contains(
        "Working with `ail` in this project",
    ));
}

#[test]
fn agent_guide_starts_with_generated_marker() {
    let (mut cmd, _home) = common::ail_cmd_isolated();
    cmd.arg("agent-guide");

    cmd.assert().success().stdout(predicates::str::starts_with(
        "<!-- Generated by `ail agent-guide`",
    ));
}

#[test]
fn agent_guide_points_at_compact_spec_reference() {
    let (mut cmd, _home) = common::ail_cmd_isolated();
    cmd.arg("agent-guide");

    cmd.assert()
        .success()
        .stdout(predicates::str::contains("ail spec --format compact"));
}

#[test]
fn agent_guide_explains_validation_loop() {
    let (mut cmd, _home) = common::ail_cmd_isolated();
    cmd.arg("agent-guide");

    cmd.assert()
        .success()
        .stdout(predicates::str::contains("ail validate"))
        .stdout(predicates::str::contains("ail materialize"));
}

#[test]
fn agent_guide_agents_md_alias_succeeds() {
    let (mut cmd, _home) = common::ail_cmd_isolated();
    cmd.args(["agent-guide", "--format", "agents-md"]);

    cmd.assert().success();
}

#[test]
fn agent_guide_unknown_format_exits_nonzero() {
    let (mut cmd, _home) = common::ail_cmd_isolated();
    cmd.args(["agent-guide", "--format", "readme"]);

    cmd.assert().failure().stderr(
        predicates::str::contains("unknown agent-guide format")
            .and(predicates::str::contains("readme")),
    );
}
