version: "0.0.1"
defaults:
  model: qwen3.5:0.8b
  provider:
    # note to use localhost in WSL you must first create a file called
    # .wslconfig in your windows home directory and include the lines
    #    [wsl2]
    #    networkingMode=mirrored
    base_url: http://localhost:11434
    auth_token: ollama
pipeline:
  - id: invocation
    prompt: "{{ session.invocation_prompt }}"
  - id: review
    prompt: |
      this is a demo - repeat the last sentence of the following:
      <previous_result>
        {{ step.invocation.result }}
      </previous_result>